export const REGISTER_SUCCESS = "AUTH::REGISTER_SUCCESS";
export const REGISTER_FAIL = "AUTH::REGISTER_FAIL";
export const LOGIN_SUCCESS = "AUTH::LOGIN_SUCCESS";
export const LOGIN_FAIL = "AUTH::LOGIN_FAIL";
export const LOGOUT = "AUTH::LOGOUT";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH::AUTH_FAIL";

export const USER_AVATAR_UPDATED = "AUTH::USER_AVATAR_UPDATED";
export const USER_DESC_UPDATED = "AUTH::USER_DESC_UPDATED";
export const LOGOUT_SUCCESS = "AUTH::LOGOUT_SUCCESS";

export const AUTH_ERROR = "AUTH::AUTH_ERROR";
