export const CREATE_CHANNEL = "CHANNELS::CREATE_CHANNEL";
export const DELETE_CHANNEL = "CHANNELS::DELETE_CHANNEL";

export const IS_ONLINE = "IS_ONLINE";
export const IS_OFFLINE = "IS_OFFLINE";

export const GET_CHANNELS = "CHANNELS::GET_CHANNELS";
export const GET_ALL_CHANNELS = "CHANNELS::GET_ALL_CHANNELS";

export const CLEAR_CHANNELS = "CHANNELS:CLEAR_CHANNELS";

export const SET_SELECTED_CHANNEL = "CHANNELS::SET_SELECTED_CHANNEL";
export const ADD_CHANNEL_USERS = "CHANNELS::ADD_CHANNEL_USERS";
export const SET_USERS_IN_ROOM = "CHANNELS::SET_USERS_IN_ROOM";
export const ADD_USER_TO_ROOM = "CHANNELS::ADD_USER_TO_ROOM";
