export const GET_PROFILE_REQUEST = "USER_PROFILE::GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "USER_PROFILE::GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "USER_PROFILE::GET_PROFILE_FAILURE";
