export const GET_PROFILE_REQUEST = "PROFILE::GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "PROFILE::GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "PROFILE::GET_PROFILE_FAILURE";
